from __future__ import annotations
import os
from typing import Any, List
from syntax import (
    NumberLit, StringLit, VarRef, Interp, BinOp, InputGet, FnCall,
    LetStmt, AssignStmt, PrintStmt, RepeatStmt, FnDef, BringStmt,
)


class CompileError(Exception):
    pass


class Compiler:
    def __init__(self):
        self.lines:  List[str] = []
        self.indent: int       = 0
        self.consts: set       = set()   # track const names for reassignment check

    # ─── emitter helpers ─────────────────────────────────────────────────────

    def emit(self, line: str):
        self.lines.append("    " * self.indent + line)

    def emit_blank(self):
        self.lines.append("")

    # ─── top level ───────────────────────────────────────────────────────────

    def compile(self, stmts: List[Any]) -> str:
        self.emit("# Generated by idot compiler (prod mode)")
        self.emit("import sys")
        self.emit_blank()
        for stmt in stmts:
            self.compile_stmt(stmt)
        return "\n".join(self.lines)

    # ─── statement compilation ───────────────────────────────────────────────
    # Add new statement nodes here (matching what parse_stmt returns).

    def compile_stmt(self, node: Any):
        t = type(node)

        if t == LetStmt:
            val = self.compile_expr(node.value)
            self.emit(f"{node.name} = {val}")
            if node.const:
                self.consts.add(node.name)

        elif t == AssignStmt:
            if node.name in self.consts:
                raise CompileError(f"Cannot reassign const {node.name!r}")
            self.emit(f"{node.name} = {self.compile_expr(node.value)}")

        elif t == PrintStmt:
            parts = []
            for a in node.args:
                if isinstance(a, Interp):
                    parts.append(f"str({a.name})")
                else:
                    parts.append(f"str({self.compile_expr(a)})")
            self.emit(f"print(' '.join([{', '.join(parts)}]))")

        elif t == RepeatStmt:
            count = self.compile_expr(node.count)
            self.emit(f"for _i in range(int({count})):")
            self.indent += 1
            for s in node.body:
                self.compile_stmt(s)
            self.indent -= 1
            self.emit_blank()

        elif t == FnDef:
            params = ", ".join(node.params)
            self.emit_blank()
            self.emit(f"def {node.name}({params}):")
            self.indent += 1
            body = node.body
            for i, s in enumerate(body):
                # Last statement in fn body becomes an implicit return
                is_last = (i == len(body) - 1)
                is_expr = not isinstance(s, (LetStmt, AssignStmt, PrintStmt,
                                             RepeatStmt, BringStmt, FnDef))
                if is_last and is_expr:
                    self.emit(f"return {self.compile_expr(s)}")
                else:
                    self.compile_stmt(s)
            self.indent -= 1
            self.emit_blank()

        elif t == FnCall:
            self.emit(self.compile_expr(node))

        elif t == BringStmt:
            self.compile_bring(node)

        elif isinstance(node, (BinOp, VarRef, NumberLit, StringLit)):
            # Bare expression as statement
            self.emit(self.compile_expr(node))

    # ─── expression compilation ──────────────────────────────────────────────
    # Returns a Python expression string (no trailing newline).

    def compile_expr(self, node: Any) -> str:
        t = type(node)

        if t == NumberLit: return repr(node.value)
        if t == StringLit: return repr(node.value)
        if t == VarRef:    return node.name
        if t == Interp:    return node.name
        if t == InputGet:  return "input()"

        if t == BinOp:
            l = self.compile_expr(node.left)
            r = self.compile_expr(node.right)
            return f"({l} {node.op} {r})"

        if t == FnCall:
            args = ", ".join(self.compile_expr(a) for a in node.args)
            return f"{node.name}({args})"

        return repr(node)

    # ─── bring compilation ───────────────────────────────────────────────────

    def compile_bring(self, node: BringStmt):
        if node.kind == "builtin":
            self.emit(f"# bring builtin: {node.alias}")

        elif node.kind == "idot":
            if node.symbol:
                self.emit(f"# bring {{{node.symbol}}} from {node.path!r} as {node.alias}")
            else:
                self.emit(f"# bring {node.path!r} as {node.alias}")

        elif node.kind == "external":
            if node.lang == "py":
                # Dynamically load a Python file at runtime
                self.emit("try:")
                self.indent += 1
                self.emit("import importlib.util as _ilu")
                self.emit(f'_spec = _ilu.spec_from_file_location("{node.alias}", "{node.path}")')
                self.emit(f"{node.alias} = _ilu.module_from_spec(_spec)")
                self.emit(f"_spec.loader.exec_module({node.alias})")
                self.indent -= 1
                self.emit("except Exception as _e:")
                self.indent += 1
                self.emit(f'print(f"[bring] WARNING: could not load {node.path!r}: " + str(_e))')
                self.indent -= 1

            elif node.lang == "js":
                self.emit(
                    f"# bring(js) {node.path!r} as {node.alias}"
                    " — JS interop not supported in compiled output"
                )
